apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-bunn
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-min-side-bunn-secrets
  image: {{version}}
  port: 7100
  liveness:
    path: /tms-min-side-bunn/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-bunn/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-bunn/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://person.intern.nav.no/tms-min-side-bunn"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
